import type { Task } from "./types";

export const MOCK_TASKS: Task[] = [
    {
        assignee: {
            avatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
            name: "octocat",
        },
        deadline: "2026-07-20",
        description: "Wire GitHub OAuth callback and session persist.",
        id: "TASK-101",
        labelIds: ["seed-bug", "seed-auth"],
        priority: "high",
        status: "todo",
        title: "Auth callback hardening",
    },
    {
        assignee: { name: "mira" },
        id: "TASK-102",
        labelIds: ["seed-ux"],
        priority: "low",
        status: "todo",
        title: "Empty state for zero repos",
    },
    {
        assignee: {
            avatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
            name: "defunkt",
        },
        branchName: "feature/TASK-110-kanban-grid",
        deadline: "2026-07-18",
        id: "TASK-110",
        labelIds: ["seed-feature"],
        priority: "urgent",
        status: "in_progress",
        title: "Kanban column layout",
    },
    {
        assignee: { name: "lin" },
        branchName: "fix/TASK-111-card-truncation",
        id: "TASK-111",
        labelIds: ["seed-bug", "seed-ux"],
        priority: "medium",
        status: "in_progress",
        title: "Truncate long task titles",
    },
    {
        assignee: {
            avatarUrl: "https://avatars.githubusercontent.com/u/3?v=4",
            name: "pjhyett",
        },
        branchName: "feature/TASK-120-pr-sync",
        deadline: "2026-07-25",
        id: "TASK-120",
        labelIds: ["seed-feature"],
        pr: {
            number: 42,
            state: "open",
            url: "https://github.com/example/plotops/pull/42",
        },
        priority: "high",
        status: "in_review",
        title: "PR status chip on cards",
    },
    {
        assignee: { name: "kai" },
        branchName: "fix/TASK-121-auth-redirect",
        id: "TASK-121",
        labelIds: ["seed-bug", "seed-auth"],
        pr: {
            number: 41,
            state: "closed",
            url: "https://github.com/example/plotops/pull/41",
        },
        priority: "medium",
        status: "in_review",
        title: "Closed PR still linked",
    },
    {
        assignee: { name: "sam" },
        branchName: "chore/TASK-130-seed-demo",
        id: "TASK-130",
        labelIds: ["seed-chore"],
        pr: {
            number: 38,
            state: "merged",
            url: "https://github.com/example/plotops/pull/38",
        },
        priority: "low",
        status: "done",
        title: "Seed demo tasks",
    },
];
