/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as mainRouteRouteImport } from './../routes/(main)/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as mainSettingsRouteImport } from './../routes/(main)/settings'
import { Route as mainHomeRouteImport } from './../routes/(main)/home'
import { Route as mainDashboardRouteImport } from './../routes/(main)/dashboard'
import { Route as mainAboutRouteImport } from './../routes/(main)/about'
import { Route as authSignInRouteImport } from './../routes/(auth)/sign-in'
import { Route as mainProjectsProjectIdRouteRouteImport } from './../routes/(main)/projects/$projectId/route'
import { Route as mainProjectsProjectIdIndexRouteImport } from './../routes/(main)/projects/$projectId/index'
import { Route as mainProjectsProjectIdSettingsRouteImport } from './../routes/(main)/projects/$projectId/settings'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainSettingsRoute = mainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainHomeRoute = mainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardRoute = mainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAboutRoute = mainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const mainProjectsProjectIdRouteRoute =
  mainProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainProjectsProjectIdIndexRoute =
  mainProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainProjectsProjectIdRouteRoute,
  } as any)
const mainProjectsProjectIdSettingsRoute =
  mainProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => mainProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof mainAboutRoute
  '/dashboard': typeof mainDashboardRoute
  '/home': typeof mainHomeRoute
  '/settings': typeof mainSettingsRoute
  '/projects/$projectId': typeof mainProjectsProjectIdRouteRouteWithChildren
  '/projects/$projectId/settings': typeof mainProjectsProjectIdSettingsRoute
  '/projects/$projectId/': typeof mainProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof mainAboutRoute
  '/dashboard': typeof mainDashboardRoute
  '/home': typeof mainHomeRoute
  '/settings': typeof mainSettingsRoute
  '/projects/$projectId/settings': typeof mainProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof mainProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(main)/about': typeof mainAboutRoute
  '/(main)/dashboard': typeof mainDashboardRoute
  '/(main)/home': typeof mainHomeRoute
  '/(main)/settings': typeof mainSettingsRoute
  '/(main)/projects/$projectId': typeof mainProjectsProjectIdRouteRouteWithChildren
  '/(main)/projects/$projectId/settings': typeof mainProjectsProjectIdSettingsRoute
  '/(main)/projects/$projectId/': typeof mainProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/about'
    | '/dashboard'
    | '/home'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/about'
    | '/dashboard'
    | '/home'
    | '/settings'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/(auth)/sign-in'
    | '/(main)/about'
    | '/(main)/dashboard'
    | '/(main)/home'
    | '/(main)/settings'
    | '/(main)/projects/$projectId'
    | '/(main)/projects/$projectId/settings'
    | '/(main)/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainRouteRoute: typeof mainRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/settings': {
      id: '/(main)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof mainSettingsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/home': {
      id: '/(main)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof mainHomeRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/about': {
      id: '/(main)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainAboutRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/projects/$projectId': {
      id: '/(main)/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof mainProjectsProjectIdRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/projects/$projectId/': {
      id: '/(main)/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof mainProjectsProjectIdIndexRouteImport
      parentRoute: typeof mainProjectsProjectIdRouteRoute
    }
    '/(main)/projects/$projectId/settings': {
      id: '/(main)/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof mainProjectsProjectIdSettingsRouteImport
      parentRoute: typeof mainProjectsProjectIdRouteRoute
    }
  }
}

interface mainProjectsProjectIdRouteRouteChildren {
  mainProjectsProjectIdSettingsRoute: typeof mainProjectsProjectIdSettingsRoute
  mainProjectsProjectIdIndexRoute: typeof mainProjectsProjectIdIndexRoute
}

const mainProjectsProjectIdRouteRouteChildren: mainProjectsProjectIdRouteRouteChildren =
  {
    mainProjectsProjectIdSettingsRoute: mainProjectsProjectIdSettingsRoute,
    mainProjectsProjectIdIndexRoute: mainProjectsProjectIdIndexRoute,
  }

const mainProjectsProjectIdRouteRouteWithChildren =
  mainProjectsProjectIdRouteRoute._addFileChildren(
    mainProjectsProjectIdRouteRouteChildren,
  )

interface mainRouteRouteChildren {
  mainAboutRoute: typeof mainAboutRoute
  mainDashboardRoute: typeof mainDashboardRoute
  mainHomeRoute: typeof mainHomeRoute
  mainSettingsRoute: typeof mainSettingsRoute
  mainProjectsProjectIdRouteRoute: typeof mainProjectsProjectIdRouteRouteWithChildren
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAboutRoute: mainAboutRoute,
  mainDashboardRoute: mainDashboardRoute,
  mainHomeRoute: mainHomeRoute,
  mainSettingsRoute: mainSettingsRoute,
  mainProjectsProjectIdRouteRoute: mainProjectsProjectIdRouteRouteWithChildren,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainRouteRoute: mainRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
