/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as mainHomeRouteImport } from './../routes/(main)/home'
import { Route as mainDashboardRouteImport } from './../routes/(main)/dashboard'
import { Route as mainAboutRouteImport } from './../routes/(main)/about'
import { Route as authSignInRouteImport } from './../routes/(auth)/sign-in'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainHomeRoute = mainHomeRouteImport.update({
  id: '/(main)/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardRoute = mainDashboardRouteImport.update({
  id: '/(main)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAboutRoute = mainAboutRouteImport.update({
  id: '/(main)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof mainAboutRoute
  '/dashboard': typeof mainDashboardRoute
  '/home': typeof mainHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof mainAboutRoute
  '/dashboard': typeof mainDashboardRoute
  '/home': typeof mainHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(main)/about': typeof mainAboutRoute
  '/(main)/dashboard': typeof mainDashboardRoute
  '/(main)/home': typeof mainHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/about' | '/dashboard' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/about' | '/dashboard' | '/home'
  id:
    | '__root__'
    | '/'
    | '/(auth)/sign-in'
    | '/(main)/about'
    | '/(main)/dashboard'
    | '/(main)/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authSignInRoute: typeof authSignInRoute
  mainAboutRoute: typeof mainAboutRoute
  mainDashboardRoute: typeof mainDashboardRoute
  mainHomeRoute: typeof mainHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/home': {
      id: '/(main)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof mainHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/about': {
      id: '/(main)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authSignInRoute: authSignInRoute,
  mainAboutRoute: mainAboutRoute,
  mainDashboardRoute: mainDashboardRoute,
  mainHomeRoute: mainHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
