/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as TermsRouteImport } from './../routes/terms'
import { Route as PrivacyRouteImport } from './../routes/privacy'
import { Route as CompleteProfileRouteImport } from './../routes/complete-profile'
import { Route as mainRouteRouteImport } from './../routes/(main)/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as InviteTokenRouteImport } from './../routes/invite.$token'
import { Route as mainSettingsRouteImport } from './../routes/(main)/settings'
import { Route as mainNotificationsRouteImport } from './../routes/(main)/notifications'
import { Route as mainHomeRouteImport } from './../routes/(main)/home'
import { Route as mainDashboardRouteImport } from './../routes/(main)/dashboard'
import { Route as mainAboutRouteImport } from './../routes/(main)/about'
import { Route as authSignUpRouteImport } from './../routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './../routes/(auth)/sign-in'
import { Route as mainProjectsProjectIdRouteRouteImport } from './../routes/(main)/projects/$projectId/route'
import { Route as mainTeamsTeamIdIndexRouteImport } from './../routes/(main)/teams/$teamId/index'
import { Route as mainProjectsProjectIdIndexRouteImport } from './../routes/(main)/projects/$projectId/index'
import { Route as mainTeamsTeamIdSettingsRouteImport } from './../routes/(main)/teams/$teamId/settings'
import { Route as mainProjectsProjectIdSettingsRouteImport } from './../routes/(main)/projects/$projectId/settings'
import { Route as mainProjectsProjectIdCiCdRouteImport } from './../routes/(main)/projects/$projectId/ci-cd'
import { Route as mainProjectsProjectIdBoardsBoardIdRouteImport } from './../routes/(main)/projects/$projectId/boards/$boardId'
import { Route as mainProjectsProjectIdBoardsBoardIdIndexRouteImport } from './../routes/(main)/projects/$projectId/boards/$boardId/index'
import { Route as mainProjectsProjectIdBoardsBoardIdBacklogRouteImport } from './../routes/(main)/projects/$projectId/boards/$boardId/backlog'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const mainSettingsRoute = mainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainNotificationsRoute = mainNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainHomeRoute = mainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardRoute = mainDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAboutRoute = mainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const mainProjectsProjectIdRouteRoute =
  mainProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainTeamsTeamIdIndexRoute = mainTeamsTeamIdIndexRouteImport.update({
  id: '/teams/$teamId/',
  path: '/teams/$teamId/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainProjectsProjectIdIndexRoute =
  mainProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainProjectsProjectIdRouteRoute,
  } as any)
const mainTeamsTeamIdSettingsRoute = mainTeamsTeamIdSettingsRouteImport.update({
  id: '/teams/$teamId/settings',
  path: '/teams/$teamId/settings',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainProjectsProjectIdSettingsRoute =
  mainProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => mainProjectsProjectIdRouteRoute,
  } as any)
const mainProjectsProjectIdCiCdRoute =
  mainProjectsProjectIdCiCdRouteImport.update({
    id: '/ci-cd',
    path: '/ci-cd',
    getParentRoute: () => mainProjectsProjectIdRouteRoute,
  } as any)
const mainProjectsProjectIdBoardsBoardIdRoute =
  mainProjectsProjectIdBoardsBoardIdRouteImport.update({
    id: '/boards/$boardId',
    path: '/boards/$boardId',
    getParentRoute: () => mainProjectsProjectIdRouteRoute,
  } as any)
const mainProjectsProjectIdBoardsBoardIdIndexRoute =
  mainProjectsProjectIdBoardsBoardIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainProjectsProjectIdBoardsBoardIdRoute,
  } as any)
const mainProjectsProjectIdBoardsBoardIdBacklogRoute =
  mainProjectsProjectIdBoardsBoardIdBacklogRouteImport.update({
    id: '/backlog',
    path: '/backlog',
    getParentRoute: () => mainProjectsProjectIdBoardsBoardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/about': typeof mainAboutRoute
  '/dashboard': typeof mainDashboardRoute
  '/home': typeof mainHomeRoute
  '/notifications': typeof mainNotificationsRoute
  '/settings': typeof mainSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$projectId': typeof mainProjectsProjectIdRouteRouteWithChildren
  '/projects/$projectId/ci-cd': typeof mainProjectsProjectIdCiCdRoute
  '/projects/$projectId/settings': typeof mainProjectsProjectIdSettingsRoute
  '/teams/$teamId/settings': typeof mainTeamsTeamIdSettingsRoute
  '/projects/$projectId/': typeof mainProjectsProjectIdIndexRoute
  '/teams/$teamId/': typeof mainTeamsTeamIdIndexRoute
  '/projects/$projectId/boards/$boardId': typeof mainProjectsProjectIdBoardsBoardIdRouteWithChildren
  '/projects/$projectId/boards/$boardId/backlog': typeof mainProjectsProjectIdBoardsBoardIdBacklogRoute
  '/projects/$projectId/boards/$boardId/': typeof mainProjectsProjectIdBoardsBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/about': typeof mainAboutRoute
  '/dashboard': typeof mainDashboardRoute
  '/home': typeof mainHomeRoute
  '/notifications': typeof mainNotificationsRoute
  '/settings': typeof mainSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$projectId/ci-cd': typeof mainProjectsProjectIdCiCdRoute
  '/projects/$projectId/settings': typeof mainProjectsProjectIdSettingsRoute
  '/teams/$teamId/settings': typeof mainTeamsTeamIdSettingsRoute
  '/projects/$projectId': typeof mainProjectsProjectIdIndexRoute
  '/teams/$teamId': typeof mainTeamsTeamIdIndexRoute
  '/projects/$projectId/boards/$boardId/backlog': typeof mainProjectsProjectIdBoardsBoardIdBacklogRoute
  '/projects/$projectId/boards/$boardId': typeof mainProjectsProjectIdBoardsBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(main)/about': typeof mainAboutRoute
  '/(main)/dashboard': typeof mainDashboardRoute
  '/(main)/home': typeof mainHomeRoute
  '/(main)/notifications': typeof mainNotificationsRoute
  '/(main)/settings': typeof mainSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/(main)/projects/$projectId': typeof mainProjectsProjectIdRouteRouteWithChildren
  '/(main)/projects/$projectId/ci-cd': typeof mainProjectsProjectIdCiCdRoute
  '/(main)/projects/$projectId/settings': typeof mainProjectsProjectIdSettingsRoute
  '/(main)/teams/$teamId/settings': typeof mainTeamsTeamIdSettingsRoute
  '/(main)/projects/$projectId/': typeof mainProjectsProjectIdIndexRoute
  '/(main)/teams/$teamId/': typeof mainTeamsTeamIdIndexRoute
  '/(main)/projects/$projectId/boards/$boardId': typeof mainProjectsProjectIdBoardsBoardIdRouteWithChildren
  '/(main)/projects/$projectId/boards/$boardId/backlog': typeof mainProjectsProjectIdBoardsBoardIdBacklogRoute
  '/(main)/projects/$projectId/boards/$boardId/': typeof mainProjectsProjectIdBoardsBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-profile'
    | '/privacy'
    | '/terms'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/dashboard'
    | '/home'
    | '/notifications'
    | '/settings'
    | '/invite/$token'
    | '/projects/$projectId'
    | '/projects/$projectId/ci-cd'
    | '/projects/$projectId/settings'
    | '/teams/$teamId/settings'
    | '/projects/$projectId/'
    | '/teams/$teamId/'
    | '/projects/$projectId/boards/$boardId'
    | '/projects/$projectId/boards/$boardId/backlog'
    | '/projects/$projectId/boards/$boardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/privacy'
    | '/terms'
    | '/sign-in'
    | '/sign-up'
    | '/about'
    | '/dashboard'
    | '/home'
    | '/notifications'
    | '/settings'
    | '/invite/$token'
    | '/projects/$projectId/ci-cd'
    | '/projects/$projectId/settings'
    | '/teams/$teamId/settings'
    | '/projects/$projectId'
    | '/teams/$teamId'
    | '/projects/$projectId/boards/$boardId/backlog'
    | '/projects/$projectId/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/complete-profile'
    | '/privacy'
    | '/terms'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(main)/about'
    | '/(main)/dashboard'
    | '/(main)/home'
    | '/(main)/notifications'
    | '/(main)/settings'
    | '/invite/$token'
    | '/(main)/projects/$projectId'
    | '/(main)/projects/$projectId/ci-cd'
    | '/(main)/projects/$projectId/settings'
    | '/(main)/teams/$teamId/settings'
    | '/(main)/projects/$projectId/'
    | '/(main)/teams/$teamId/'
    | '/(main)/projects/$projectId/boards/$boardId'
    | '/(main)/projects/$projectId/boards/$boardId/backlog'
    | '/(main)/projects/$projectId/boards/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainRouteRoute: typeof mainRouteRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/settings': {
      id: '/(main)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof mainSettingsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/notifications': {
      id: '/(main)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof mainNotificationsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/home': {
      id: '/(main)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof mainHomeRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/about': {
      id: '/(main)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof mainAboutRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/projects/$projectId': {
      id: '/(main)/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof mainProjectsProjectIdRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/teams/$teamId/': {
      id: '/(main)/teams/$teamId/'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId/'
      preLoaderRoute: typeof mainTeamsTeamIdIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/projects/$projectId/': {
      id: '/(main)/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof mainProjectsProjectIdIndexRouteImport
      parentRoute: typeof mainProjectsProjectIdRouteRoute
    }
    '/(main)/teams/$teamId/settings': {
      id: '/(main)/teams/$teamId/settings'
      path: '/teams/$teamId/settings'
      fullPath: '/teams/$teamId/settings'
      preLoaderRoute: typeof mainTeamsTeamIdSettingsRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/projects/$projectId/settings': {
      id: '/(main)/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof mainProjectsProjectIdSettingsRouteImport
      parentRoute: typeof mainProjectsProjectIdRouteRoute
    }
    '/(main)/projects/$projectId/ci-cd': {
      id: '/(main)/projects/$projectId/ci-cd'
      path: '/ci-cd'
      fullPath: '/projects/$projectId/ci-cd'
      preLoaderRoute: typeof mainProjectsProjectIdCiCdRouteImport
      parentRoute: typeof mainProjectsProjectIdRouteRoute
    }
    '/(main)/projects/$projectId/boards/$boardId': {
      id: '/(main)/projects/$projectId/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/projects/$projectId/boards/$boardId'
      preLoaderRoute: typeof mainProjectsProjectIdBoardsBoardIdRouteImport
      parentRoute: typeof mainProjectsProjectIdRouteRoute
    }
    '/(main)/projects/$projectId/boards/$boardId/': {
      id: '/(main)/projects/$projectId/boards/$boardId/'
      path: '/'
      fullPath: '/projects/$projectId/boards/$boardId/'
      preLoaderRoute: typeof mainProjectsProjectIdBoardsBoardIdIndexRouteImport
      parentRoute: typeof mainProjectsProjectIdBoardsBoardIdRoute
    }
    '/(main)/projects/$projectId/boards/$boardId/backlog': {
      id: '/(main)/projects/$projectId/boards/$boardId/backlog'
      path: '/backlog'
      fullPath: '/projects/$projectId/boards/$boardId/backlog'
      preLoaderRoute: typeof mainProjectsProjectIdBoardsBoardIdBacklogRouteImport
      parentRoute: typeof mainProjectsProjectIdBoardsBoardIdRoute
    }
  }
}

interface mainProjectsProjectIdBoardsBoardIdRouteChildren {
  mainProjectsProjectIdBoardsBoardIdBacklogRoute: typeof mainProjectsProjectIdBoardsBoardIdBacklogRoute
  mainProjectsProjectIdBoardsBoardIdIndexRoute: typeof mainProjectsProjectIdBoardsBoardIdIndexRoute
}

const mainProjectsProjectIdBoardsBoardIdRouteChildren: mainProjectsProjectIdBoardsBoardIdRouteChildren =
  {
    mainProjectsProjectIdBoardsBoardIdBacklogRoute:
      mainProjectsProjectIdBoardsBoardIdBacklogRoute,
    mainProjectsProjectIdBoardsBoardIdIndexRoute:
      mainProjectsProjectIdBoardsBoardIdIndexRoute,
  }

const mainProjectsProjectIdBoardsBoardIdRouteWithChildren =
  mainProjectsProjectIdBoardsBoardIdRoute._addFileChildren(
    mainProjectsProjectIdBoardsBoardIdRouteChildren,
  )

interface mainProjectsProjectIdRouteRouteChildren {
  mainProjectsProjectIdCiCdRoute: typeof mainProjectsProjectIdCiCdRoute
  mainProjectsProjectIdSettingsRoute: typeof mainProjectsProjectIdSettingsRoute
  mainProjectsProjectIdIndexRoute: typeof mainProjectsProjectIdIndexRoute
  mainProjectsProjectIdBoardsBoardIdRoute: typeof mainProjectsProjectIdBoardsBoardIdRouteWithChildren
}

const mainProjectsProjectIdRouteRouteChildren: mainProjectsProjectIdRouteRouteChildren =
  {
    mainProjectsProjectIdCiCdRoute: mainProjectsProjectIdCiCdRoute,
    mainProjectsProjectIdSettingsRoute: mainProjectsProjectIdSettingsRoute,
    mainProjectsProjectIdIndexRoute: mainProjectsProjectIdIndexRoute,
    mainProjectsProjectIdBoardsBoardIdRoute:
      mainProjectsProjectIdBoardsBoardIdRouteWithChildren,
  }

const mainProjectsProjectIdRouteRouteWithChildren =
  mainProjectsProjectIdRouteRoute._addFileChildren(
    mainProjectsProjectIdRouteRouteChildren,
  )

interface mainRouteRouteChildren {
  mainAboutRoute: typeof mainAboutRoute
  mainDashboardRoute: typeof mainDashboardRoute
  mainHomeRoute: typeof mainHomeRoute
  mainNotificationsRoute: typeof mainNotificationsRoute
  mainSettingsRoute: typeof mainSettingsRoute
  mainProjectsProjectIdRouteRoute: typeof mainProjectsProjectIdRouteRouteWithChildren
  mainTeamsTeamIdSettingsRoute: typeof mainTeamsTeamIdSettingsRoute
  mainTeamsTeamIdIndexRoute: typeof mainTeamsTeamIdIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAboutRoute: mainAboutRoute,
  mainDashboardRoute: mainDashboardRoute,
  mainHomeRoute: mainHomeRoute,
  mainNotificationsRoute: mainNotificationsRoute,
  mainSettingsRoute: mainSettingsRoute,
  mainProjectsProjectIdRouteRoute: mainProjectsProjectIdRouteRouteWithChildren,
  mainTeamsTeamIdSettingsRoute: mainTeamsTeamIdSettingsRoute,
  mainTeamsTeamIdIndexRoute: mainTeamsTeamIdIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainRouteRoute: mainRouteRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
